Repository Mukjipsa/Mukjipsa-iOS, pull requests merged in 2022-11, with the labels that each got.

#8 [Setting] #7 - Slack 연동 확인
  .github/PULL_REQUEST_TEMPLATE.md
  Mukjipsa-iOS/Mukjipsa-iOS.xcodeproj/project.pbxproj
  Mukjipsa-iOS/Mukjipsa-iOS/Resource/Support/SceneDelegate.swift
  Mukjipsa-iOS/Mukjipsa-iOS/Screen/Screen.swift
  Mukjipsa-iOS/Mukjipsa-iOS/Screen/TabBar/BookMark/BookMarkViewController.swift
  Mukjipsa-iOS/Mukjipsa-iOS/Screen/TabBar/MyIngredient/MyIngredientViewController.swift
  Mukjipsa-iOS/Mukjipsa-iOS/Screen/TabBar/Recipe/RecipeViewController.swift
  Mukjipsa-iOS/Mukjipsa-iOS/Screen/TabBar/TabBar/TabBarController.swift
Labels: 황인성

#11 [Add] 컬러, 이미지 에셋 추가
  Mukjipsa-iOS/Mukjipsa-iOS.xcodeproj/project.pbxproj
  Mukjipsa-iOS/Mukjipsa-iOS/Global/Constant/Constant.swift
  Mukjipsa-iOS/Mukjipsa-iOS/Global/Constant/Image.swift
  Mukjipsa-iOS/Mukjipsa-iOS/Global/Extension/UIColor+.swift
  Mukjipsa-iOS/Mukjipsa-iOS/Resource/Asset/Assets.xcassets/AppIcon.appiconset/Contents.json
  Mukjipsa-iOS/Mukjipsa-iOS/Resource/Asset/Assets.xcassets/bookmark.imageset/Contents.json
  Mukjipsa-iOS/Mukjipsa-iOS/Resource/Asset/Assets.xcassets/bookmark.imageset/bookmark.png
  Mukjipsa-iOS/Mukjipsa-iOS/Resource/Asset/Assets.xcassets/bookmark.imageset/bookmark@2x.png
  Mukjipsa-iOS/Mukjipsa-iOS/Resource/Asset/Assets.xcassets/bookmark.imageset/bookmark@3x.png
  Mukjipsa-iOS/Mukjipsa-iOS/Resource/Asset/Assets.xcassets/bookmarkSelected.imageset/Contents.json
  Mukjipsa-iOS/Mukjipsa-iOS/Resource/Asset/Assets.xcassets/bookmarkSelected.imageset/bookmarkSelected.png
  Mukjipsa-iOS/Mukjipsa-iOS/Resource/Asset/Assets.xcassets/bookmarkSelected.imageset/bookmarkSelected@2x.png
  Mukjipsa-iOS/Mukjipsa-iOS/Resource/Asset/Assets.xcassets/bookmarkSelected.imageset/bookmarkSelected@3x.png
Labels: 황인성, Add

#12 [Add] Mukjipsa#9 - 폰트 추가
  Mukjipsa-iOS/Mukjipsa-iOS.xcodeproj/project.pbxproj
  Mukjipsa-iOS/Mukjipsa-iOS.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Mukjipsa-iOS/Mukjipsa-iOS/Global/Extension/UIFont+.swift
Labels: Add, 강효진

#18 [Chore] #17 - .gitignore 수정
  .gitignore
Labels: 황인성, 수정

#15 [Add] #14 - Typography lineHeight, letterSpacing 설정
  Mukjipsa-iOS/Mukjipsa-iOS.xcodeproj/project.pbxproj
  Mukjipsa-iOS/Mukjipsa-iOS.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Mukjipsa-iOS/Mukjipsa-iOS/Global/Constant/LetterSpacing.swift
  Mukjipsa-iOS/Mukjipsa-iOS/Global/Extension/UIButton+.swift
  Mukjipsa-iOS/Mukjipsa-iOS/Global/Extension/UILabel+.swift
  Mukjipsa-iOS/Mukjipsa-iOS/Global/Extension/UITextField+.swift
  Mukjipsa-iOS/Mukjipsa-iOS/Global/Extension/UITextView+.swift
  Mukjipsa-iOS/Mukjipsa-iOS/Resource/Support/Info.plist
  Mukjipsa-iOS/Mukjipsa-iOS/Screen/TabBar/Recipe/RecipeViewController.swift
Labels: Add, 강효진

#22 [Chore] #16- BaseVC, BaseView
  Mukjipsa-iOS/Mukjipsa-iOS/Global/Base/BaseView.swift
  Mukjipsa-iOS/Mukjipsa-iOS/Global/BaseViewController.swift
Labels: 황인성, 수정

#23 [Feat] #13- MJSButton 구현
  Mukjipsa-iOS/Mukjipsa-iOS.xcodeproj/project.pbxproj
  Mukjipsa-iOS/Mukjipsa-iOS/Global/DesignSystem/DesignSystem.swift
  Mukjipsa-iOS/Mukjipsa-iOS/Global/DesignSystem/MJSButton.swift
  Mukjipsa-iOS/Mukjipsa-iOS/Global/Extension/UIColor+.swift
Labels: 황인성, DesignSystem

#25 [Design] #20 - 온보딩 기본재료 입력 뷰 UI 구현
  Mukjipsa-iOS/Mukjipsa-iOS.xcodeproj/project.pbxproj
  Mukjipsa-iOS/Mukjipsa-iOS.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Mukjipsa-iOS/Mukjipsa-iOS/Global/Base/BaseViewController.swift
  Mukjipsa-iOS/Mukjipsa-iOS/Global/Constant/Image.swift
  Mukjipsa-iOS/Mukjipsa-iOS/Global/Constant/String.swift
  Mukjipsa-iOS/Mukjipsa-iOS/Global/Extension/UIButton+.swift
  Mukjipsa-iOS/Mukjipsa-iOS/Global/Extension/UIFont+.swift
  Mukjipsa-iOS/Mukjipsa-iOS/Global/Extension/UILabel+.swift
  Mukjipsa-iOS/Mukjipsa-iOS/Global/Extension/UITextField+.swift
  Mukjipsa-iOS/Mukjipsa-iOS/Global/Protocol/UICollectionViewRegisterable.swift
  Mukjipsa-iOS/Mukjipsa-iOS/Global/Protocol/UITableViewRegisterable.swift
  Mukjipsa-iOS/Mukjipsa-iOS/Global/Utils/getClassName.swift
  Mukjipsa-iOS/Mukjipsa-iOS/Resource/Asset/Assets.xcassets/icBack.imageset/Contents.json
  Mukjipsa-iOS/Mukjipsa-iOS/Resource/Asset/Assets.xcassets/icBack.imageset/icon.png
  Mukjipsa-iOS/Mukjipsa-iOS/Resource/Asset/Assets.xcassets/icBack.imageset/icon@2x.png
  Mukjipsa-iOS/Mukjipsa-iOS/Resource/Asset/Assets.xcassets/icBack.imageset/icon@3x.png
  Mukjipsa-iOS/Mukjipsa-iOS/Resource/Support/Info.plist
  Mukjipsa-iOS/Mukjipsa-iOS/Resource/Support/SceneDelegate.swift
  Mukjipsa-iOS/Mukjipsa-iOS/Screen/Common/OnboardingNaviView.swift
  Mukjipsa-iOS/Mukjipsa-iOS/Screen/Common/OnboardingTitleView.swift
  Mukjipsa-iOS/Mukjipsa-iOS/Screen/Onboarding/Cells/IngredientCollectionViewCell.swift
  Mukjipsa-iOS/Mukjipsa-iOS/Screen/Onboarding/ViewControllers/BasicIngredientViewController.swift
  Mukjipsa-iOS/Mukjipsa-iOS/Screen/Onboarding/ViewModel/BasicIngredientModel.swift
  Mukjipsa-iOS/Mukjipsa-iOS/Screen/Onboarding/Views/BasicIngredientView.swift
  Mukjipsa-iOS/Mukjipsa-iOS/Screen/TabBar/Recipe/RecipeViewController.swift
Labels: 강효진, Design

#27 [Design] #26 - 로그인 뷰 UI 구현
  Mukjipsa-iOS/Mukjipsa-iOS.xcodeproj/project.pbxproj
  Mukjipsa-iOS/Mukjipsa-iOS/Global/Constant/Image.swift
  Mukjipsa-iOS/Mukjipsa-iOS/Resource/Asset/Assets.xcassets/Auth/Contents.json
  Mukjipsa-iOS/Mukjipsa-iOS/Resource/Asset/Assets.xcassets/Auth/imgLogo.imageset/Contents.json
  Mukjipsa-iOS/Mukjipsa-iOS/Resource/Asset/Assets.xcassets/Auth/imgLogo.imageset/imgLogin.png
  Mukjipsa-iOS/Mukjipsa-iOS/Resource/Asset/Assets.xcassets/Auth/imgLogo.imageset/imgLogin@2x.png
  Mukjipsa-iOS/Mukjipsa-iOS/Resource/Asset/Assets.xcassets/Auth/imgLogo.imageset/imgLogin@3x.png
  Mukjipsa-iOS/Mukjipsa-iOS/Resource/Asset/Assets.xcassets/Auth/kakaoLoginButton.imageset/Contents.json
  Mukjipsa-iOS/Mukjipsa-iOS/Resource/Asset/Assets.xcassets/Auth/kakaoLoginButton.imageset/cta.png
  Mukjipsa-iOS/Mukjipsa-iOS/Resource/Asset/Assets.xcassets/Auth/kakaoLoginButton.imageset/cta@2x.png
  Mukjipsa-iOS/Mukjipsa-iOS/Resource/Asset/Assets.xcassets/Auth/kakaoLoginButton.imageset/cta@3x.png
  Mukjipsa-iOS/Mukjipsa-iOS/Resource/Support/SceneDelegate.swift
  Mukjipsa-iOS/Mukjipsa-iOS/Screen/Auth/Login/View/LoginView.swift
  Mukjipsa-iOS/Mukjipsa-iOS/Screen/Auth/Login/ViewController/LoginViewController.swift
Labels: 강효진, Design

#29 [Chore] #21 - 파일 추가 및 수정
  Mukjipsa-iOS/Mukjipsa-iOS.xcodeproj/project.pbxproj
  Mukjipsa-iOS/Mukjipsa-iOS/Global/Extension/UIViewController+.swift
  Mukjipsa-iOS/Mukjipsa-iOS/Network/Base/APIConstants.swift
Labels: 황인성, 수정

#34 [Add] #10 - 폰트파일 파일 트리 경로 수정
  Mukjipsa-iOS/Mukjipsa-iOS.xcodeproj/project.pbxproj
  Mukjipsa-iOS/Mukjipsa-iOS/Resource/Font/Pretendard-Light.otf
  Mukjipsa-iOS/Mukjipsa-iOS/Resource/Font/Pretendard-Medium.otf
  Mukjipsa-iOS/Mukjipsa-iOS/Resource/Font/Pretendard-Regular.otf
  Mukjipsa-iOS/Mukjipsa-iOS/Resource/Font/Pretendard-SemiBold.otf
Labels: Add, 강효진

#37 [Design] #36 - 스플래시 뷰 UI 구현
  Mukjipsa-iOS/Mukjipsa-iOS.xcodeproj/project.pbxproj
  Mukjipsa-iOS/Mukjipsa-iOS/Global/Constant/Image.swift
  Mukjipsa-iOS/Mukjipsa-iOS/Resource/Asset/Assets.xcassets/Splash/Contents.json
  Mukjipsa-iOS/Mukjipsa-iOS/Resource/Asset/Assets.xcassets/Splash/MJSlogo.imageset/Contents.json
  Mukjipsa-iOS/Mukjipsa-iOS/Resource/Asset/Assets.xcassets/Splash/MJSlogo.imageset/Frame 2608242.png
  Mukjipsa-iOS/Mukjipsa-iOS/Resource/Asset/Assets.xcassets/Splash/MJSlogo.imageset/Frame 2608242@2x.png
  Mukjipsa-iOS/Mukjipsa-iOS/Resource/Asset/Assets.xcassets/Splash/MJSlogo.imageset/Frame 2608242@3x.png
  Mukjipsa-iOS/Mukjipsa-iOS/Resource/Support/SceneDelegate.swift
  Mukjipsa-iOS/Mukjipsa-iOS/Screen/Splash/View/SplashView.swift
  Mukjipsa-iOS/Mukjipsa-iOS/Screen/Splash/ViewController/SplashViewController.swift
Labels: 강효진, Design

#41 [Design] #38 - 육류/해산물 입력 뷰 UI 구현
  Mukjipsa-iOS/Mukjipsa-iOS.xcodeproj/project.pbxproj
  Mukjipsa-iOS/Mukjipsa-iOS/Global/Constant/Image.swift
  Mukjipsa-iOS/Mukjipsa-iOS/Global/Constant/String.swift
  Mukjipsa-iOS/Mukjipsa-iOS/Resource/Asset/Assets.xcassets/Onboarding/Contents.json
  Mukjipsa-iOS/Mukjipsa-iOS/Resource/Asset/Assets.xcassets/Onboarding/icCheck.imageset/Contents.json
  Mukjipsa-iOS/Mukjipsa-iOS/Resource/Asset/Assets.xcassets/Onboarding/icCheck.imageset/icCheck.png
  Mukjipsa-iOS/Mukjipsa-iOS/Resource/Asset/Assets.xcassets/Onboarding/icCheck.imageset/icCheck@2x.png
  Mukjipsa-iOS/Mukjipsa-iOS/Resource/Asset/Assets.xcassets/Onboarding/icCheck.imageset/icCheck@3x.png
  Mukjipsa-iOS/Mukjipsa-iOS/Resource/Asset/Assets.xcassets/Onboarding/progressBarFour.imageset/Contents.json
  Mukjipsa-iOS/Mukjipsa-iOS/Resource/Asset/Assets.xcassets/Onboarding/progressBarFour.imageset/progressBar4.png
  Mukjipsa-iOS/Mukjipsa-iOS/Resource/Asset/Assets.xcassets/Onboarding/progressBarFour.imageset/progressBar4@2x.png
  Mukjipsa-iOS/Mukjipsa-iOS/Resource/Asset/Assets.xcassets/Onboarding/progressBarFour.imageset/progressBar4@3x.png
  Mukjipsa-iOS/Mukjipsa-iOS/Resource/Asset/Assets.xcassets/Onboarding/progressBarOne.imageset/Contents.json
  Mukjipsa-iOS/Mukjipsa-iOS/Resource/Asset/Assets.xcassets/Onboarding/progressBarOne.imageset/progressBar.png
  Mukjipsa-iOS/Mukjipsa-iOS/Resource/Asset/Assets.xcassets/Onboarding/progressBarOne.imageset/progressBar@2x.png
  Mukjipsa-iOS/Mukjipsa-iOS/Resource/Asset/Assets.xcassets/Onboarding/progressBarOne.imageset/progressBar@3x.png
  Mukjipsa-iOS/Mukjipsa-iOS/Resource/Asset/Assets.xcassets/Onboarding/progressBarThree.imageset/Contents.json
  Mukjipsa-iOS/Mukjipsa-iOS/Resource/Asset/Assets.xcassets/Onboarding/progressBarThree.imageset/progressBar3.png
  Mukjipsa-iOS/Mukjipsa-iOS/Resource/Asset/Assets.xcassets/Onboarding/progressBarThree.imageset/progressBar3@2x.png
  Mukjipsa-iOS/Mukjipsa-iOS/Resource/Asset/Assets.xcassets/Onboarding/progressBarThree.imageset/progressBar3@3x.png
  Mukjipsa-iOS/Mukjipsa-iOS/Resource/Asset/Assets.xcassets/Onboarding/progressBarTwo.imageset/Contents.json
  Mukjipsa-iOS/Mukjipsa-iOS/Resource/Asset/Assets.xcassets/Onboarding/progressBarTwo.imageset/progressBar2.png
  Mukjipsa-iOS/Mukjipsa-iOS/Resource/Asset/Assets.xcassets/Onboarding/progressBarTwo.imageset/progressBar2@2x.png
  Mukjipsa-iOS/Mukjipsa-iOS/Resource/Asset/Assets.xcassets/Onboarding/progressBarTwo.imageset/progressBar2@3x.png
  Mukjipsa-iOS/Mukjipsa-iOS/Resource/Support/SceneDelegate.swift
  Mukjipsa-iOS/Mukjipsa-iOS/Screen/Common/Onboarding/Cells/OnboardingCollectionViewCell.swift
  Mukjipsa-iOS/Mukjipsa-iOS/Screen/Common/Onboarding/Cells/OnboardingTitleViewCell.swift
  Mukjipsa-iOS/Mukjipsa-iOS/Screen/Common/Onboarding/Views/OnboardingCollectionViewSectionFooter.swift
  Mukjipsa-iOS/Mukjipsa-iOS/Screen/Common/Onboarding/Views/OnboardingCollectionViewSectionHeader.swift
  Mukjipsa-iOS/Mukjipsa-iOS/Screen/Common/Onboarding/Views/OnboardingNaviView.swift
  Mukjipsa-iOS/Mukjipsa-iOS/Screen/Common/Onboarding/Views/ProgressBarImageView.swift
  Mukjipsa-iOS/Mukjipsa-iOS/Screen/Onboarding/BasicIngredient/Cells/BasicIngredientCollectionViewCell.swift
  Mukjipsa-iOS/Mukjipsa-iOS/Screen/Onboarding/BasicIngredient/View/BasicIngredientView.swift
  Mukjipsa-iOS/Mukjipsa-iOS/Screen/Onboarding/MeatAndSeaFood/View/MeatAndSeaFoodView.swift
  Mukjipsa-iOS/Mukjipsa-iOS/Screen/Onboarding/MeatAndSeaFood/ViewConstroller/MeatAndSeaFoodViewController.swift
  Mukjipsa-iOS/Mukjipsa-iOS/Screen/Onboarding/MeatAndSeaFood/ViewModel/MeatAndSeaModel.swift
Labels: 강효진, Design

#44 [Design] #30 - MyRecipe UI 구현
  Mukjipsa-iOS/Mukjipsa-iOS.xcodeproj/project.pbxproj
  Mukjipsa-iOS/Mukjipsa-iOS/Global/Constant/String.swift
  Mukjipsa-iOS/Mukjipsa-iOS/Global/Extension/CALayer+.swift
  Mukjipsa-iOS/Mukjipsa-iOS/Resource/Support/SceneDelegate.swift
  Mukjipsa-iOS/Mukjipsa-iOS/Screen/Common/NaviView/RecipeNaviView.swift
  Mukjipsa-iOS/Mukjipsa-iOS/Screen/TabBar/Recipe/MyIngredientRecipe/Cell/RecipeCollelctionViewCell.swift
  Mukjipsa-iOS/Mukjipsa-iOS/Screen/TabBar/Recipe/MyIngredientRecipe/Cell/RecipeTagCell.swift
  Mukjipsa-iOS/Mukjipsa-iOS/Screen/TabBar/Recipe/MyIngredientRecipe/View/RecipeHeaderView.swift
  Mukjipsa-iOS/Mukjipsa-iOS/Screen/TabBar/Recipe/MyIngredientRecipe/ViewController/MyRecipeViewController.swift
  Mukjipsa-iOS/Mukjipsa-iOS/Screen/TabBar/Recipe/RecipeModel/RecipeModel.swift
  Mukjipsa-iOS/Mukjipsa-iOS/Screen/TabBar/Recipe/RecipeViewController.swift
  Mukjipsa-iOS/Mukjipsa-iOS/Screen/TabBar/TabBar/TabBarController.swift
Labels: 황인성, Design

#51 [Feat] #50 - Empty View 구현
  Mukjipsa-iOS/Mukjipsa-iOS.xcodeproj/project.pbxproj
  Mukjipsa-iOS/Mukjipsa-iOS/Global/Extension/UITextField+.swift
  Mukjipsa-iOS/Mukjipsa-iOS/Global/Extension/UIViewController+.swift
  Mukjipsa-iOS/Mukjipsa-iOS/Screen/Common/NaviView/RecipeNaviView.swift
  Mukjipsa-iOS/Mukjipsa-iOS/Screen/TabBar/Recipe/RecipeEmpty/BookmarkEmptyViewController.swift
  Mukjipsa-iOS/Mukjipsa-iOS/Screen/TabBar/Recipe/RecipeEmpty/RecipeEmptyViewController.swift
  Mukjipsa-iOS/Mukjipsa-iOS/Screen/TabBar/Recipe/RecipeEmpty/SearchEmptyViewController.swift
  Mukjipsa-iOS/Mukjipsa-iOS/Screen/TabBar/Recipe/Reuse/EmptyView.swift
  Mukjipsa-iOS/Mukjipsa-iOS/Screen/TabBar/Recipe/Reuse/RecipeCollelctionViewCell.swift
  Mukjipsa-iOS/Mukjipsa-iOS/Screen/TabBar/Recipe/Reuse/SearchHeaderView.swift
Labels: 황인성, Feat

#53 [Add] #10 - 로티, 엠티뷰 에셋 추가
  Mukjipsa-iOS/Mukjipsa-iOS.xcodeproj/project.pbxproj
  Mukjipsa-iOS/Mukjipsa-iOS/Global/Constant/Image.swift
  Mukjipsa-iOS/Mukjipsa-iOS/Global/Constant/Lottie.swift
  Mukjipsa-iOS/Mukjipsa-iOS/Resource/Asset/Assets.xcassets/imgEmptyBookmark.imageset/Contents.json
  Mukjipsa-iOS/Mukjipsa-iOS/Resource/Asset/Assets.xcassets/imgEmptyBookmark.imageset/img_empty_bookmark.png
  Mukjipsa-iOS/Mukjipsa-iOS/Resource/Asset/Assets.xcassets/imgEmptyBookmark.imageset/img_empty_bookmark@2x.png
  Mukjipsa-iOS/Mukjipsa-iOS/Resource/Asset/Assets.xcassets/imgEmptyBookmark.imageset/img_empty_bookmark@3x.png
  Mukjipsa-iOS/Mukjipsa-iOS/Resource/Asset/Assets.xcassets/imgEmptyRecipe.imageset/Contents.json
  Mukjipsa-iOS/Mukjipsa-iOS/Resource/Asset/Assets.xcassets/imgEmptyRecipe.imageset/img_empty_recipe.png
  Mukjipsa-iOS/Mukjipsa-iOS/Resource/Asset/Assets.xcassets/imgEmptyRecipe.imageset/img_empty_recipe@2x.png
  Mukjipsa-iOS/Mukjipsa-iOS/Resource/Asset/Assets.xcassets/imgEmptyRecipe.imageset/img_empty_recipe@3x.png
  Mukjipsa-iOS/Mukjipsa-iOS/Resource/Asset/Assets.xcassets/imgEmptySearch.imageset/Contents.json
  Mukjipsa-iOS/Mukjipsa-iOS/Resource/Asset/Assets.xcassets/imgEmptySearch.imageset/img_empty_search.png
  Mukjipsa-iOS/Mukjipsa-iOS/Resource/Asset/Assets.xcassets/imgEmptySearch.imageset/img_empty_search@2x.png
  Mukjipsa-iOS/Mukjipsa-iOS/Resource/Asset/Assets.xcassets/imgEmptySearch.imageset/img_empty_search@3x.png
Labels: 황인성, Feat

#54 [Fix] #10 - Confilct 해결
  Mukjipsa-iOS/Mukjipsa-iOS.xcodeproj/project.pbxproj
Labels: 황인성, Fix
